[pytest]
DJANGO_SETTINGS_MODULE = config.settings.teste
python_files = test_*.py
testpaths = tests apps/contas/tests apps/empresas/tests apps/auditoria/tests apps/ajuda/tests apps/ia/tests apps/whatsapp/tests
