"""Cria os modelos e indices iniciais do atendimento."""

# Generated by Django 5.2.17 on 2026-08-27 14:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Instala contatos, conversas, mensagens e suas invariantes."""

    initial = True

    dependencies = [
        ("empresas", "0002_configuracao_empresa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(blank=True, default="", max_length=160)),
                ("numero_normalizado", models.CharField(max_length=30)),
                (
                    "observacoes",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("primeiro_contato_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_contato_em", models.DateTimeField(blank=True, null=True)),
                ("excluido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contatos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ("nome", "numero_normalizado", "id"),
            },
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[("IA", "IA"), ("HUMANO", "Humano")],
                        default="IA",
                        max_length=7,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABERTA", "Aberta"), ("FINALIZADA", "Finalizada")],
                        default="ABERTA",
                        max_length=10,
                    ),
                ),
                ("contagem_nao_lida", models.PositiveIntegerField(default=0)),
                ("finalizada_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversas",
                        to="atendimento.contato",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversas",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ("-atualizado_em", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direcao",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saida")],
                        max_length=7,
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        choices=[
                            ("CLIENTE", "Cliente"),
                            ("IA", "IA"),
                            ("ATENDENTE", "Atendente"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=9,
                    ),
                ),
                ("texto", models.TextField(max_length=4096)),
                (
                    "identificador_externo",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEBIDA", "Recebida"),
                            ("PENDENTE", "Pendente"),
                            ("ENVIADA", "Enviada"),
                            ("ENTREGUE", "Entregue"),
                            ("FALHA", "Falha"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "erro_sanitizado",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("entregue_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="atendimento.conversa",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ("criado_em", "id"),
            },
        ),
        migrations.AddField(
            model_name="conversa",
            name="ultima_mensagem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="atendimento.mensagem",
            ),
        ),
        migrations.AddIndex(
            model_name="contato",
            index=models.Index(
                fields=["empresa", "excluido_em", "numero_normalizado"],
                name="atend_contato_busca_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contato",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero_normalizado"),
                name="atend_contato_empresa_numero_unico",
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["empresa", "conversa", "criado_em", "id"],
                name="atend_mensagem_hist_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mensagem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identificador_externo", ""), _negated=True),
                fields=("empresa", "identificador_externo"),
                name="atend_mensagem_externa_unica",
            ),
        ),
        migrations.AddIndex(
            model_name="conversa",
            index=models.Index(
                fields=["empresa", "estado", "-atualizado_em", "-id"],
                name="atend_conversa_lista_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ABERTA")),
                fields=("empresa", "contato"),
                name="atend_conversa_aberta_unica",
            ),
        ),
    ]
