"""Cria a configuracao unica de WhatsApp por empresa."""

# Generated by Django 5.2.17 on 2026-08-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Cria os campos operacionais sem persistir credenciais em claro."""

    initial = True

    dependencies = [
        ("empresas", "0002_configuracao_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_base", models.URLField(max_length=500)),
                ("nome_instancia", models.CharField(max_length=120)),
                (
                    "chave_api_criptografada",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("ativo", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DESCONECTADO", "DESCONECTADO"),
                            ("AGUARDANDO_QR", "AGUARDANDO_QR"),
                            ("CONECTADO", "CONECTADO"),
                            ("ERRO", "ERRO"),
                        ],
                        default="DESCONECTADO",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_whatsapp",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
