"""Cria a preferencia visual isolada por empresa e usuario."""

# Generated by Django 5.2.17 on 2026-08-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adiciona paleta e luminosidade persistentes ao dominio de contas."""

    dependencies = [
        ("contas", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciaVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[
                            ("azul", "Azul"),
                            ("esmeralda", "Esmeralda"),
                            ("violeta", "Violeta"),
                            ("rubi", "Rubi"),
                            ("ambar", "Ambar"),
                        ],
                        default="azul",
                        max_length=10,
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("CLARO", "Claro"),
                            ("ESCURO", "Escuro"),
                            ("SISTEMA", "Sistema"),
                        ],
                        default="SISTEMA",
                        max_length=7,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_visuais",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_visuais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "usuario"),
                        name="preferencia_visual_empresa_usuario_unica",
                    )
                ],
            },
        ),
    ]
