# Generated by Django 5.2.17 on 2026-08-25

"""Adiciona o perfil operacional e a versao da empresa."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Inclui os campos usados no atendimento e no prompt da IA."""

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="descricao",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="empresa",
            name="endereco",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="empresa",
            name="horario_atendimento",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="empresa",
            name="instrucoes_atendimento",
            field=models.TextField(blank=True, default="", max_length=4000),
        ),
        migrations.AddField(
            model_name="empresa",
            name="segmento",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="empresa",
            name="site",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="empresa",
            name="telefone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
