# Generated by Django 5.2.17 on 2026-08-29

"""Adiciona o fuso horario operacional de cada empresa."""

from django.db import migrations, models

import apps.empresas.models.empresa


class Migration(migrations.Migration):
    """Persiste o identificador IANA usado nas metricas diarias."""

    dependencies = [
        ("empresas", "0002_configuracao_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="fuso_horario",
            field=models.CharField(
                default="America/Rio_Branco",
                max_length=64,
                validators=(apps.empresas.models.empresa.validar_fuso_horario,),
            ),
        ),
    ]
