"""Cria documentos textuais e perguntas frequentes por empresa."""

# Generated by Django 5.2.17 on 2026-08-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Persiste a base textual de conhecimento do modulo de IA."""

    dependencies = [
        ("empresas", "0002_configuracao_empresa"),
        ("ia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoTextual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField(max_length=50000)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("excluido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_textuais",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ("ordem", "pk"),
                "indexes": [
                    models.Index(
                        fields=["empresa", "excluido_em", "ativo", "ordem"],
                        name="ia_doc_contexto_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerguntaFrequente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.CharField(max_length=500)),
                ("resposta", models.TextField(max_length=10000)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("excluido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas_frequentes",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ("ordem", "pk"),
                "indexes": [
                    models.Index(
                        fields=["empresa", "excluido_em", "ativo", "ordem"],
                        name="ia_faq_contexto_idx",
                    )
                ],
            },
        ),
    ]
