"""Cria as tabelas iniciais de eventos e revisoes de auditoria."""

# Generated by Django 5.2.17 on 2026-08-24 17:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica o esquema inicial imutavel da auditoria."""

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisaoObjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_objeto", models.CharField(max_length=120)),
                ("objeto_id", models.CharField(max_length=64)),
                ("numero", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisoes_objetos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={"ordering": ("-numero", "-criado_em")},
        ),
        migrations.CreateModel(
            name="EventoAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_objeto", models.CharField(max_length=120)),
                ("objeto_id", models.CharField(max_length=64)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIACAO", "Criacao"),
                            ("ATUALIZACAO", "Atualizacao"),
                            ("EXCLUSAO", "Exclusao"),
                            ("RESTAURACAO", "Restauracao"),
                        ],
                        max_length=12,
                    ),
                ),
                ("antes", models.JSONField(default=dict)),
                ("depois", models.JSONField(default=dict)),
                ("campos_alterados", models.JSONField(default=list)),
                ("origem", models.CharField(max_length=80)),
                ("correlacao", models.CharField(max_length=80)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_auditoria",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "revisao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evento",
                        to="auditoria.revisaoobjeto",
                    ),
                ),
            ],
            options={"ordering": ("-criado_em", "-pk")},
        ),
        migrations.AddConstraint(
            model_name="revisaoobjeto",
            constraint=models.UniqueConstraint(
                fields=("empresa", "tipo_objeto", "objeto_id", "numero"),
                name="revisao_objeto_numero_unico",
            ),
        ),
    ]
