"""Configura managers protegidas como managers-base da auditoria."""

# Generated by Django 5.2.17 on 2026-08-24 17:50

from django.db import migrations


class Migration(migrations.Migration):
    """Registra as opções append-only no estado dos modelos."""

    dependencies = [("auditoria", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="eventoauditoria",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ("-criado_em", "-pk"),
            },
        ),
        migrations.AlterModelOptions(
            name="revisaoobjeto",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ("-numero", "-criado_em"),
            },
        ),
    ]
